# Wifi Sensor Package
# Uncomment include in skyfan_dc.yaml

substitutions:
  wifi_signal_name: "${friendly_name} WIFI Signal"
  wifi_uptime_name: "${friendly_name} Uptime"
  wifi_ip_name: "${friendly_name} IP"
  wifi_ssid_name: "${friendly_name} SSID"
  wifi_mac_name: "${friendly_name} MAC"
  





sensor:
  - platform: wifi_signal
    name: ${wifi_signal_name}
    update_interval: 60s
    disabled_by_default: true


text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${wifi_ip_name}
      disabled_by_default: true
    ssid:
      name: ${wifi_ssid_name}
      disabled_by_default: true
    mac_address:
      name: ${wifi_mac_name}   
      disabled_by_default: true
      
  - platform: uptime
    name: ${wifi_uptime_name}
    update_interval: 30s
    disabled_by_default: true            