# SkyFan DC - 5 Speed Fan package
#
# This package make the fan act as a 5 speed fan in home Assistant
# Fan is really a 5 speed fan with a weird 6th speed via eco mode
# Fan mode is also exported to Home Assistant
#
# Does this by mapping the speeds as follows
#   1 = Speed 1
#   2 = Speed 2
#   3 = Speed 3
#   4 = Speed 4
#   5 = Speed 5
#
# 5 physical speeds
# Expose to Home Assistant as 5 discrete speeds

substitutions:
  skyfan_fan_name: "${friendly_name} Fan"
  fan_mode_name: "${friendly_name} Mode"  
  fan_timer_name: "${friendly_name} Timer"   
  fan_power_name: "${friendly_name} Fan Power"


    # Uses the new INTEGER speed datapoint support
fan:
  - platform: tuya
    name: ${skyfan_fan_name}
    id: skyfan_fan
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: false    
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 5
    direction_datapoint: 8
    
    # Trigger power update when fan state or speed changes
    on_turn_on:
      then:
        - component.update: fan_power
    on_turn_off:
      then:
        - component.update: fan_power
    on_speed_set:
      then:
        - component.update: fan_power    

select:
  # Fan modes
  - platform: tuya
    name: ${fan_mode_name}
    id: skyfan_mode
    enum_datapoint: 2
    optimistic: true
    disabled_by_default: true
    options:
      0: Normal
      1: Eco
      2: Sleep
    on_value:
      then:
        - component.update: fan_power   # update power when Eco/Normal mode changes
        

  # Run timer 1h..12h
  - platform: tuya
    name: ${fan_timer_name}
    id: skyfan_timer
    enum_datapoint: 22
    optimistic: true
    disabled_by_default: true
    options:
      0: "Off"
      1: 1h
      2: 2h
      3: 3h
      4: 4h
      5: 5h
      6: 6h
      7: 7h
      8: 8h
      9: 9h
      10: 10h
      11: 11h
      12: 12h




# Faux Fan Power Sensor Package
# Based on original code by: James Eggleston
#
# Exposes a faux Power sensor (Watts) based on SkyFan DC datasheets.
# Select the model by setting the substitution `skyfan_model` to one of:
#   SKY903, SKY1203, SKY1303, SKY1503, SKY1204, SKY1404
#
# IMPORTANT:
# - Set `skyfan_model` WITHOUT quotes so it can be used as a C++ array name.
# - This reads the current speed from the fan component id `skyfan_fan`.


sensor:
  - id: fan_power
    platform: template
    name: ${fan_power_name}
    update_interval: 30s
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
    accuracy_decimals: 1
    lambda: |-
      // Index 0 is OFF, 1..5 are speeds 1..5, 6 is eco mode
      static const float SKY903[7]   = {0,3,7,12,19.5,32,4.8};
      static const float SKY1203[7]  = {0,3.6,8,15,22,32.5,5.4};
      static const float SKY1303[7]  = {0,3.9,9,15.6,25.2,31.8,5.8};
      static const float SKY1503[7]  = {0,3.9,16,26,44.2,6,9};
      static const float SKY1204[7]  = {0,3.8,9,17,27,30,5.8};
      static const float SKY1404[7]  = {0,3.5,8,15,23,38,5.5};

      int s = (int) id(skyfan_fan).speed;
      if (id(skyfan_mode).current_option() == (std::string) "Eco") {
        s = 6;
      }     
      return ${skyfan_model}[s];
    disabled_by_default: true